version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_test
    ports:
      - "5435:5432"  # Map port 5432 in the container to port 5433 on the host

  backend:
    build:
      context: C:/Users/saradenno/Downloads/sara (6) 3/demo
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Testdatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"















#version: '3.8'
#
#services:
#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: Testdatabase
#    ports:
#      - "5435:5432"  # Map port 5432 in the container to port 5435 on the host
#
#  backend:
#    build:
#      context: C:/Users/saradenno/Downloads/sara (6) 3/demo
#      dockerfile: Dockerfile
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Testdatabase
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: "true"
#      SERVER_PORT: 8080
#      SERVER_SERVLET_CONTEXT_PATH: /api
#      JWT_SECRET: Ireallylovepuppiestheyarethebest**
#      JWT_EXPIRATION: 3600000
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
